version: '3'
services:
  todoback:
    build: ./todo-app/back-end
    restart: always
    ports:
      - 3001:3001
  todofront:
    build: ./todo-app/front-end #  Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: always
    ports:
      - 3000:3000 # primeiro parâmetro é sempre a porta do computador local e o segundo parâmetro é a porta exposta no container.
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  todotests:
    build: ./todo-app/tests # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: always
    environment:
      - FRONT_HOST=todofront # conseguimos configurar as variáveis de ambiente em nossos serviços do Compose.
    depends_on:
      - todoback
      - todofront