version: '3'
services:
  frontend:
    build: frontend/ # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    restart: always
    ports:
      - 3000:3000 # primeiro parâmetro é sempre a porta do computador local e o segundo parâmetro é a porta exposta no container.
    depends_on:
      - backend
    volumes:
      - ./logs:/var/log/frontend    # caminho no computador : caminho no container
  backend:
    build: backend/
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database # conseguimos configurar as variáveis de ambiente em nossos serviços do Compose.
    depends_on:
      - database # dependências entre os serviços!
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1    # Especificamos a Imagem Docker diretamente.
    restart: always
    volumes:
      - dados-do-banco:/data/db
    networks:
      - rede-virtual-2
volumes:
  dados-do-banco: # nome do disco virtual : caminho no container
networks:
  rede-virtual-1:
  rede-virtual-2: